package net.nintendo.automation.email;

public enum EmailTemplate {
    TEMPLATE_EMAIL_PLANNED_SUBMISSION_DATE_PAST,
    TEMPLATE_EMAIL_RELEASE_ROM_UPLOAD_FAILURE,
    TEMPLATE_EMAIL_COMPANY_FINANCIAL_PAYEE_INFORMATION_ADDED_EXTERNAL,
    F8,
    TEMPLATE_EMAIL_COMPANY_FINANCIAL_PAYEE_INFORMATION_UPDATED_EXTERNAL,
    TEMPLATE_EMAIL_LOTCHECK_QUEUE_SUBMISSION_JUDGEMENT_SET_OK_FOR_PARTNER,
    TEMPLATE_EMAIL_LOTCHECK_QUEUE_SUBMISSION_JUDGEMENT_SET_NOT_OK_FOR_PARTNER,
    TEMPLATE_EMAIL_PARTNER_JUDGMENT_REVERT,
    TEMPLATE_EMAIL_SALES_JUDGMENT_REVERT
}
